#!/usr/bin/env node
//
// Sync this repository's plugin sources into OpenCode's global plugin
// discovery directory (~/.config/opencode/plugins/opusage/).
//
// The panel imports @opencode/plugin, @opencode/theme, and the OpenTUI
// packages, which OpenCode does NOT resolve for you — so this also symlinks
// the repository's node_modules into the plugin directory (run `npm install`
// here first if it doesn't exist yet).
//
// OpenCode watches the discovery directory and reconciles on file changes, so
// no restart is usually needed; if the TUI is closed, just reopen it.
//
import { cpSync, existsSync, lstatSync, mkdirSync, readlinkSync, rmSync, symlinkSync, writeFileSync } from "node:fs"
import os from "node:os"
import path from "node:path"

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..")
const configDir =
  process.env.XDG_CONFIG_HOME != null
    ? path.join(process.env.XDG_CONFIG_HOME, "opencode", "plugins", "opusage")
    : path.join(os.homedir(), ".config", "opencode", "plugins", "opusage")

mkdirSync(configDir, { recursive: true })
cpSync(path.join(root, "src", "server.ts"), path.join(configDir, "index.ts"))
cpSync(path.join(root, "src", "tui.tsx"), path.join(configDir, "panel.tsx"))
writeFileSync(
  path.join(configDir, "tui.ts"),
  "// TUI entrypoint for the discovered opusage plugin (generated by scripts/devlink.mjs)\n" +
    'export { default } from "./panel.tsx"\n',
)

// Make the panel's dependencies resolvable from the plugin directory.
const link = path.join(configDir, "node_modules")
const repoModules = path.join(root, "node_modules")
if (!existsSync(repoModules)) {
  console.log(`opusage: plugin synced to ${configDir}`)
  console.log(`Run \`npm install\` in ${root} so the plugin's dependencies exist.`)
  process.exit(1)
}
try {
  const st = lstatSync(link)
  const correct = st.isSymbolicLink() && path.resolve(configDir, readlinkSync(link)) === repoModules
  if (!correct) rmSync(link, { recursive: true, force: true })
  if (!existsSync(link)) symlinkSync(repoModules, link)
} catch {
  symlinkSync(repoModules, link)
}

console.log(`opusage: plugin synced to ${configDir}`)
console.log(`node_modules linked -> ${repoModules}`)
console.log("OpenCode watches that directory and reloads on changes.")
