#!/usr/bin/env node
//
// Sync this repository's plugin sources into OpenCode's global plugin
// discovery directory (~/.config/opencode/plugins/opusage/).
//
// Discovered plugins get `@opencode/plugin` resolved by OpenCode at runtime,
// so this works without `npm install` and without publishing to npm.
// OpenCode loads discovered plugins at startup — restart after running this.
//
import { cpSync, mkdirSync, writeFileSync } from "node:fs"
import os from "node:os"
import path from "node:path"

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..")
const configDir =
  process.env.XDG_CONFIG_HOME != null
    ? path.join(process.env.XDG_CONFIG_HOME, "opencode", "plugins", "opusage")
    : path.join(os.homedir(), ".config", "opencode", "plugins", "opusage")

mkdirSync(configDir, { recursive: true })
cpSync(path.join(root, "src", "server.ts"), path.join(configDir, "index.ts"))
cpSync(path.join(root, "src", "tui.tsx"), path.join(configDir, "panel.tsx"))
writeFileSync(
  path.join(configDir, "tui.ts"),
  "// TUI entrypoint for the discovered opusage plugin (generated by scripts/devlink.mjs)\n" +
    'export { default } from "./panel.tsx"\n',
)

console.log(`opusage: plugin synced to ${configDir}`)
console.log("Restart OpenCode to load it.")
